---
title: "Gentrification trial R markdown"
output: html_document
date: "2023-11-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
  

```{r}
################################################################################
################################ load library ##################################
################################################################################

library(tidyverse)
library(here)
#if(!require(devtools)){install.packages("devtools")} #not sure if we need the devtools version?
#devtools::install_github("bluegreen-labs/daymetr")
library(sf)
library(daymetr)
#library(weathermetrics)
library(tidycensus) 
library(ncdf4)
library(raster)
library(exactextractr)
library(dplyr)
library(purrr)
library(ggridges)

################################################################################
################################################################################
```

```{r}
################################################################################
################################# Constants ####################################
################################################################################

ANNA_DATADIR = "anna"

DATA_DATADIR <- file.path(ANNA_DATADIR, "data")

HICDD_DATADIR <- file.path(DATA_DATADIR, "hicdd_data")

NY_BBOX = c(-74.2555,40.49843,-73.70006,40.91505)

GEOGRAPHIC_RESOLUTION = "tract"

################################################################################
################################################################################
```

```{r}
################################################################################
################################# Maintenance ##################################
################################################################################

# create data folder if it doesn't already exist
if(!dir.exists(here(DATA_DATADIR))){dir.create(here(DATA_DATADIR))}

# create a HICDD folder if it doesnt exist already
if(!dir.exists(here(HICDD_DATADIR))){dir.create(here(HICDD_DATADIR))}

#api key for census tract data
census_api_key("826252b09915d6545eff4f71dadf97b1003be92c", install = TRUE, overwrite = TRUE)

################################################################################
################################################################################
```

```{r}
################################################################################
############################# Simple Functions #################################
################################################################################

# function for converting celcius to farenheit
C_to_F <- function (T.celsius, round = 2) {
    T.fahrenheit <- (9/5) * T.celsius + 32
    T.fahrenheit <- round(T.fahrenheit, digits = round)
    
  return(T.fahrenheit)
}

# setting the threshold for HICDD
CalcTempAboveThresh <- function(temperature, threshold = 65){
  pmax(temperature, threshold) - threshold
}

################################################################################
################################################################################
```

```{r}
################################################################################
###################### Function to Download Census Data ########################
################################################################################

#DC: Is this only 2010 for now? we should add an argument to specify the year?
#># AS: only 2000, 2010, and 2020 are available for this function/package. It defaults to 2020, but 
#># 2020 doesnt have all the data available that we want, so Weixi chose 2010. 
#># here is the documentation: https://www.rdocumentation.org/packages/tidycensus/versions/1.4.1/topics/get_decennial

GetCensusData <- function(geography) { 
  census_data <- get_decennial(
    geography = geography,
    variables = c("Total_pop" = "P001001"),
    year = 2010,
    output = "wide",
    geometry = TRUE,
    state = 36
  ) %>%
    st_transform(crs = st_crs(4326)) %>%
    filter(!st_is_empty(.))
  
  return(census_data)
}

################################################################################
################################################################################
```

```{r}
################################################################################
############################# Downloading Census Data ##########################
################################################################################

census_data = GetCensusData(GEOGRAPHIC_RESOLUTION)


################################################################################
################################################################################

```

```{r}
################################################################################
########################## Calculation Functions  ##############################
################################################################################

# function to calculate saturated vapor pressure
GetSatVP <- function(t) {
  ifelse(t > 0, exp(34.494 - (4924.99/(t + 237.1)))/(t + 105)^1.57, exp(43.494 - (6545.8/(t + 278)))/(t + 868)^2)
}

# function to calculate heat index 

hi <- function(t) -42.379 + 2.04901523 * t + 10.14333127 * rh - 
        0.22475541 * t * rh - 6.83783 * 10^-3 * t^2 - 
        5.481717 * 10^-2 * rh^2 + 1.22874 * 10^-3 * t^2 * 
        rh + 8.5282 * 10^-4 * t * rh^2 - 1.99 * 10^-6 * 
        t^2 * rh^2

GetHeatIndex <- function (t = NA, rh = NA) { 
  ifelse(is.na(rh) | is.na(t) | is.nan(rh) | is.nan(t), NA,
               ifelse(t <=40, t,  
                      ifelse(-10.3 + 1.1 * t + 0.047 * rh < 79, -10.3 + 1.1 * t + 0.047 * rh,
                             ifelse(rh <= 13 & t >= 80 & t <= 112, -42.379 + 2.04901523 * t + 10.14333127 * rh - 
        0.22475541 * t * rh - 6.83783 * 10^-3 * t^2 - 
        5.481717 * 10^-2 * rh^2 + 1.22874 * 10^-3 * t^2 * 
        rh + 8.5282 * 10^-4 * t * rh^2 - 1.99 * 10^-6 * 
        t^2 * rh^2 - (13 - rh)/4 * ((17 - abs(t - 95))/17)^0.5,
                                    ifelse(rh > 85 & t >= 80 & t <= 87, -42.379 + 2.04901523 * t + 10.14333127 * rh - 
        0.22475541 * t * rh - 6.83783 * 10^-3 * t^2 - 
        5.481717 * 10^-2 * rh^2 + 1.22874 * 10^-3 * t^2 * 
        rh + 8.5282 * 10^-4 * t * rh^2 - 1.99 * 10^-6 * 
        t^2 * rh^2 + 0.02 * (rh - 85) * (87 - t), -42.379 + 2.04901523 * t + 10.14333127 * rh - 
        0.22475541 * t * rh - 6.83783 * 10^-3 * t^2 - 
        5.481717 * 10^-2 * rh^2 + 1.22874 * 10^-3 * t^2 * 
        rh + 8.5282 * 10^-4 * t * rh^2 - 1.99 * 10^-6 * 
        t^2 * rh^2)))))
}

################################################################################
################################################################################
```

```{r}
################################################################################
#################### Function for Downloading Daymet Data ######################
################################################################################

DownloadDaymetData <- function(years, location) {
  
  # Creating folders for the parameters we want, which are maximum temperature and vapor pressure
  tmax_folder <- file.path(HICDD_DATADIR, "tmax")
  vp_folder <- file.path(HICDD_DATADIR, "vp")
  
  if (!dir.exists(tmax_folder)) 
    dir.create(tmax_folder, recursive = TRUE)
  
  if (!dir.exists(vp_folder))
    dir.create(vp_folder, recursive = TRUE)
  
  # Remove years that already exist in tmax_folder
  existing_tmax_files <- list.files(tmax_folder, pattern = ".nc$", full.names = TRUE)
  existing_tmax_years <- unique(sub(".nc$", "", basename(existing_tmax_files)))
  existing_tmax_years <- gsub("^.*?([0-9]{4}).*$", "\\1", existing_tmax_years)
  years <- setdiff(years, existing_tmax_years)

  
  # Remove years that already exist in vp_folder
  existing_vp_files <- list.files(vp_folder, pattern = ".nc$", full.names = TRUE)
  existing_vp_years <- unique(sub(".nc$", "", basename(existing_vp_files)))
  existing_vp_years <- gsub("^.*?([0-9]{4}).*$", "\\1", existing_vp_years)
  years <- setdiff(years, existing_vp_years)
  
  # Check if there are remaining years to download
  if (length(years) > 0) {
    # Download maximum temperature daymet data
    download_daymet_ncss(location = location,
                        start = years[1],
                        end = years[length(years)],
                        param = c("tmax"),
                        path = tmax_folder)
  
    # Download vapor pressure daymet data
    download_daymet_ncss(location = location,
                        start = years[1],
                        end = years[length(years)],
                        param = c("vp"),
                        path = vp_folder)
  } else {
    cat("Data already exists for the specified years and location.\n")
  }
}

################################################################################
################################################################################
```

```{r}
################################################################################
########################### Downloading Daymet Data ############################
################################################################################

# years in the form start_year:end_year
  years = 2011

  DownloadDaymetData(years, NY_BBOX) 
  
#># AS: this doesn't happen for me but ill look into it.
#># if it keeps happening do a trycatch
#DC: first time I tried this it failed with the error below. Just keep track for reproducibility checks. 
  
#   Error in curl::curl_fetch_disk(url, x$path, handle = handle) :
# transfer closed with 687987262 bytes remaining to read
  
################################################################################
################################################################################
```

```{r}
################################################################################
######################### Function for Calculating HICDDs ######################
################################################################################

GetHicddsPerYear <- function(year){
  
  # defining the cooling season
  cooling_season_starts <- "-05-01"
  cooling_season_ends <- "-09-30"
  year_start_date <- as.Date(paste0(year,"-01-01"))
  cooling_season_start_index <- as.numeric(as.Date(paste0(year,cooling_season_starts)) - year_start_date)
  cooling_season_ends_index <- as.numeric(as.Date(paste0(year,cooling_season_ends)) - year_start_date)
  days_in_season <- cooling_season_ends_index - cooling_season_start_index + 1  

  # opening tmax data
  tmax <- nc_open(file.path(here(HICDD_DATADIR, "tmax", paste0("tmax_daily_", year, "_ncss.nc"))))
  tmax_array <- ncvar_get(tmax, "tmax")
  
  # fill missing values in with 0
  fillvalue <- ncatt_get(tmax, "tmax", "_FillValue")
  tmax_array[tmax_array == fillvalue$value] <- 0
  
  # extracting temperature data corresponding to cooling season
  tmax_array_cooling_season <- tmax_array[, , cooling_season_start_index:cooling_season_ends_index]
  
  # calculating vapor pressure data corresponding to cooling season
  satVP_array_cooling_season <- GetSatVP(tmax_array_cooling_season[, , seq_along(1:days_in_season)])
  
  # removing tmax_array from memory to save space
  rm(tmax_array)
  
  # opening vapor pressure data
  vp <- nc_open(file.path(here(HICDD_DATADIR, "vp", paste0("vp_daily_", year, "_ncss.nc"))))
  long_vp <- ncvar_get(vp, "x")
  lat_vp <- ncvar_get(vp, "y")
  vp_array <- ncvar_get(vp, "vp")
  
  # fill missing values in with 0
  fillvalue <- ncatt_get(vp, "vp", "_FillValue")
  vp_array[vp_array == fillvalue$value] <- 0
  
  # extracting vapor pressure data corresponding to cooling season
  vp_array_cooling_season <- vp_array[, , cooling_season_start_index:cooling_season_ends_index]
  
  # removing vp_array from memory to save space
  rm(vp_array)
  
  # converting temperature values from Celsius to Fahrenheit
  tmax_array_cooling_season_F <- C_to_F(tmax_array_cooling_season[, , seq_along(1:days_in_season)])
  
  # calculating relative humidity
  relative_humidity <- lapply(1:days_in_season, function(j) (vp_array_cooling_season[, , j] / satVP_array_cooling_season[, , j]) * 100)
  
  # storing the relative humidity values in an array
  relative_humidity <- array(unlist(relative_humidity), dim = c(854, 811, days_in_season))
  
  # calculating heat index
  heat_index <- sapply(1:days_in_season, function(j) GetHeatIndex(t = tmax_array_cooling_season_F[, , j], rh = relative_humidity[, , j]))
  
  # storing heat index values in an array
  heat_index <- array(unlist(heat_index), dim = c(854, 811, days_in_season))
  
#  relative_humidity
#  heat_index
#  dim(tmax_array_cooling_season_F)
#  dim(relative_humidity)
  
  # calculating cooling degree days per day
  cdds_per_day <- lapply(1:days_in_season, function(j) CalcTempAboveThresh(heat_index[, , j]))
  
 # cdds_per_day
  
  # calculating cooling degree days for the season
  cdds_across_summer <- matrix(nrow = 854, ncol = 811)
  cdds_across_summer[is.na(cdds_across_summer)] <- 0
  for (i in 1:days_in_season) {
    step1 <- Reduce(`+`, lapply(list(cdds_per_day[[i]], cdds_across_summer), function(x) {
      x[is.na(x)] <- 0
      x
    }))
    cdds_across_summer <- step1
  }
  
  # converting cooling degree data for the season into a raster and setting CRS
  raster_1year <- raster(t(cdds_across_summer), xmn = min(long_vp), xmx = max(long_vp), ymn = min(lat_vp),
                         ymx = max(lat_vp), crs = CRS("+proj=lcc +lat_1=25 +lat_2=60 +lat_0=42.5 +lon_0=-100 +x_0=0 +y_0=0 +ellps=WGS84 +units=km +no_defs"))
  raster_1year_epsg4326 <- projectRaster(from = raster_1year, crs = "+init=epsg:4326")
  
  # finding the CDDs per census area per year using exact_extract function
  tract_mean_cdds_1year <- exact_extract(raster_1year_epsg4326, census_data, weights = "area", fun = "mean", append_cols = TRUE) %>%
    mutate(year = year)
  
  return(tract_mean_cdds_1year)
}

################################################################################
################################################################################
```

```{r}
################################################################################
########### Get HICDDS for Specified Years and Save as Data Frame ##############
################################################################################

# array of years in the form start_year:end_year (example 2012:2015 would be 2012, 2013, 2014, and 2015)
year = 2011

# get HICDDs for specified years
hicdds <- lapply(year, GetHicddsPerYear)

# create an empty data frame to store the HICDDS
hicdds_collection <- data.frame()

# create a vector of years
years <- c(year)

# add the HICDDs to the data frame
for (i in years){
    hicdds_collection  <- bind_rows(hicdds_collection, GetHicddsPerYear(i))
  } 

# retrieve HICDDs for each year and bind them into a single data frame
hicdds_collection <- purrr::map(years, GetHicddsPerYear) %>%
  bind_rows()

#lapply(years,GetHicddsPerYear) %>%
 # bind_rows()

#purrr::map(years,GetHicddsPerYear) %>%
 # bind_rows()

# view data
hicdds_collection

################################################################################
################################################################################

```

```{r}
# save file to computer 

output_file <- file.path(here(HICDD_DATADIR), "hicdds_per_year_tract.csv")
write.csv(hicdds_collection, file = output_file)

 ### this works but I want to make sure that this code is saving the data in a way that is useful to me for using later
```




